### ISSUE TITLE
Feature request: Add typescript support

### ISSUE THREAD

**Issue by StarLederer** [sdunster/jsx-dom-factory#1]
No additional description needed.

Willing to contribute (probably will impulsively make a PR later even if I don't get a response 😅).

**Comment by sdunster** [comment]
Gladly accepting PRs :)

**Comment by StarLederer** [comment]
I've found a much more developed [repo](https://github.com/krakenjs/jsx-pragmatic) that renders JSX so think this feature request is no longer worth it.
